### PR TITLE
Fix #87 - make `expDesign` computing the design of both MTplus and MT/MST loc

### LINKED ISSUE #87: refactor `expDesignMtMst`
at version 0.3.1 is not working

### PR DESCRIPTION
**Pull request by marcobarilari**
This PR make possible to have MTplus and MT/MST localziers' design computed by the refactored function `expDeisgn`. To my knowledge, the MT/MST loc was not working at v0.3.1 .

I am pushing to master cause, as said, we do not have an official release working with MT/MST and so this will be a minor bump as v0.4.0

What do you think @Remi-Gau ?

fixes #87

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Will check it tomorrow

There is a dev branch on this repo but it seems behind master... No?

I should probably fix those failing CI too.

**Comment by marcobarilari** [comment]
Yes, `dev` is behind but not so match. Looks like `main` has been patched with a couple of things (update of the submod). Do you suggest as good practice to always pr to `dev`? In this case I can delete this one and open a new one (after rebasing `dev` to `main`) and then work like that. Though I would release the new version after this pr cause it is important it is out.

**Comment by Remi-Gau** [comment]
> Yes, `dev` is behind but not so match. Looks like `main` has been patched with a couple of things (update of the submod). Do you suggest as good practice to always pr to `dev`? In this case I can delete this one and open a new one (after rebasing `dev` to `main`) and then work like that. Though I would release the new version after this pr cause it is important it is out.

So in general `dev` should not be behind `main` or `master` so any change we apply to `main`, should be applied to `dev`: the easiest is to merge `main` into `dev`.

Also there is no need to open a new PR to change the "base" (the branch you target in a PR): if you go at the top of that PR page and click edit (right of the PR title) you can then alter the base branch. VERY useful.

I will update dev by merging main into it and will let you change the base.

**Comment by Remi-Gau** [comment]
> I will update dev by merging main into it

done

**Comment by Remi-Gau** [comment]
ok will try to see why the tests are failing

File: setParameters.m [hunk 1]
```diff
@@ -221,17 +222,14 @@
...
         cfg.design.motionType = 'radial';
         cfg.design.motionDirections = [666 -666];
-        %         cfg.design.names = {'motion'};
-        cfg.design.names = {'static'; 'motion'};
-        cfg.design.fixationPosition = {'fixation_left'; 'fixation_right'};
-        %          cfg.design.fixationPosition = {'fixation_right'; 'fixation_left'};
+        cfg.design.names = {'motion'};
+        %         cfg.design.names = {'static'; 'motion'};
+        cfg.design.fixationPosition = {'fixation_left'};
+        %         cfg.design.fixationPosition = {'fixation_right'; 'fixation_left'};
```
[the remark this answers is not in the document]
Comment (marcobarilari) [reply setParameters.m:228]: totally agree!!! This is much=needed, we might need to discuss if we want this at the level of the localizers or at CPP_PTB

File: subfun/design/expDesign.m [hunk 2]
```diff
@@ -70,6 +75,9 @@
         % Get the computed design on a visual representation
         displayFigs = 1;
 
+        % make sure we got access to all the required functions and inputs
+        run('../../initEnv.m');
```
[the remark this answers is not in the document]
Comment (marcobarilari) [reply subfun/design/expDesign.m:79]: true, this is necessary only if the script is run as a stand-alone, so the most top position is just below the if statement (line 66)

File: setParameters.m (hunk 1 above)
[the remark this answers is not in the document]
Comment (Remi-Gau) [reply setParameters.m:228]: or CPP_PTB already has a bunch of presets I think in `initPTB`, but they are not as neatly organized as in CPP_SPM so maybe starting there would be nice.

But I am sure we will need them at the localizer level too.

File: subfun/design/setSpeedTargets.m [hunk 3]
```diff
@@ -17,7 +17,7 @@
         % Outputs an "empty" matrix in case no speed task is required
     else
         [~, nbEventsPerBlock, ~, nbBlocks] = getDesignInput(cfg);
-        speeds = ones(nbBlocks, nbEventsPerBlock) * cfg.dot.speedPixPerFrame;
+        speeds = ones(nbBlocks, nbEventsPerBlock);
```
Comment (Remi-Gau) [inline subfun/design/setSpeedTargets.m:20]: I changed this:
- "fixation cross" should not have speed
- also without this change both "sides" of the `if / else` block had the same content making it effectively useless

```matlab
if A
  b = 2
else
  b = 2
end
```

File: setParameters.m (hunk 1 above)
[the remark this answers is not in the document]
Comment (marcobarilari) [reply setParameters.m:228]: actually ... #78

File: subfun/design/setSpeedTargets.m (hunk 3 above)
Comment (marcobarilari) [reply subfun/design/setSpeedTargets.m:20]: and that multiplication is actually important so will put it back

Comment (marcobarilari) [inline subfun/design/setSpeedTargets.m:20]:
```suggestion
        speeds = ones(nbBlocks, nbEventsPerBlock) * cfg.dot.speedPixPerFrame;
```

Comment (Remi-Gau) [reply subfun/design/setSpeedTargets.m:20]: ah OK then. Sorry about that. 
let's remove the IF block for now because this is confusing and add a `TODO` explaining that things need to be change there later.

File: setParameters.m (hunk 1 above)
[the remark this answers is not in the document]
Comment (Remi-Gau) [reply setParameters.m:228]: Also the one for the localizer might be smaller than the one for the whole CPP_PTB

File: subfun/design/setSpeedTargets.m (hunk 3 above)
Comment (Remi-Gau) [reply subfun/design/setSpeedTargets.m]: Done

**Comment by marcobarilari** [comment]
Adding a reminder in `getMockConfig` that if the parameters for nbRep and nbEvents are different than 12 for both the tests will fail

**Comment by Remi-Gau** [comment]
> Adding a reminder in `getMockConfig` that if the parameters for nbRep and nbEvents are different than 12 for both the tests will fail, correct?

Better would be to make the tests more flexible and read the "correct" value from the `cfg` itself. 

I won't read a comment somewhere to know why a test fails: I think I would assume that the test is failing because I change something in the code and not in the mock.

File: subfun/design/getMockConfig.m [hunk 4]
```diff
@@ -1,6 +1,9 @@
 function cfg = getMockConfig(isMT)
     % fixture
     %
+    % REMINDER: If `cfg.design.nbRepetitions` and `cfg.design.nbEventsPerBlock` values are different
+    %           from 12, tests on GitHub will fail so do not change.
```
Comment (Remi-Gau) [inline subfun/design/getMockConfig.m:5]:
```suggestion
    % REMINDER: If `cfg.design.nbRepetitions` and `cfg.design.nbEventsPerBlock` values are changed
    %           this may make the tests on GitHub fail, so be careful.
```

avoid "hard coding" values in the comment too, in case we change them in the future. :wink:

File: subfun/design/getMockConfig.m [hunk 5]
```diff
@@ -10,6 +13,13 @@
     %% Set specific localizer configurations as conditions, directions (MT) and stimulation
     %  position (MT_MST)
 
+    %% Nb blocks and events
+
+    % 2 conditions [`cfg.design.names`] and 10 repetitions [`cfg.design.nbRepetitions`]
```
Comment (Remi-Gau) [inline subfun/design/getMockConfig.m:18]: I don't think the comment matches the code here, right?

File: subfun/design/getMockConfig.m (hunk 4 above)
Comment (marcobarilari) [reply subfun/design/getMockConfig.m:5]: you right!

File: subfun/design/getMockConfig.m (hunk 5 above)
Comment (Remi-Gau) [reply subfun/design/getMockConfig.m:21]: oh ok.
Cool lets add that in!

**Comment by Remi-Gau** [comment]
fixes #91

**Review by Remi-Gau — APPROVED** [review]
Looks good to me: feel free to merge if you are happy with it

**Comment by marcobarilari** [comment]
Great! Thank you very much :) I will give it a round of try with all the task etc to check if something is broken and merge it. Will also create a release name v0.4.0. LMK if there is something I am missing

**Comment by Remi-Gau** [comment]
> Great! Thank you very much :) I will give it a round of try with all the task etc to check if something is broken and merge it. Will also create a release name v0.4.0. LMK if there is something I am missing

happy to have a new release. :-)

I had made a checklist for new releases:

https://github.com/cpp-lln-lab/.github/blob/main/release_protocol.md

> Ps: so nice to see all the checks green :)

I know, right?!
